### ISSUE TITLE
Problema com uso de ícones 

### ISSUE THREAD

**Issue by nikolai1312** [nikolai1312/To-Do#1]
# ícones em HTML 

Dentro deste projeto tive um grande problema para utilizar ícones para substituição de inputs e buttons, buscando algumas soluções na internet acabei encontrando alguns sites como [Google Fonts](https://fonts.google.com/) e o [Phosphor Icons](https://phosphoricons.com/). 
Continuo estudando para buscar a melhor implementação para estes ícones, acabei não me acostumando com essa ideia de substituição de botões, porém agora já tenho o material necessário para realizar a tarefa.

**Comment by heitorgandolfi** [comment]
Olá, Nicolas! Tudo bem?
Além do Phosphor Icons, utilizo o [Font Awesome](https://fontawesome.com/) e [Devicon](https://devicon.dev/). Também são ótimos!

**Comment by nikolai1312** [comment]
Solucionado! Utilizei os ícones do Phosphor Icons, são bem coloridos e possuem uma bela usabilidade.
